export const sportKeys = [
  'RUN',
  'SKI',
  'ILMAHIRVI',
  'ILMALUODIKKO',
  'METSASTYSHIRVI',
  'METSASTYSLUODIKKO',
  'METSASTYSHAULIKKO',
  'METSASTYSTRAP',
  'PIENOISHIRVI',
  'PIENOISLUODIKKO',
  'NORDIC',
  'EUROPEAN',
]
