window.translations = {
  allClubs: 'Kaikki seurat',
  allDistricts: 'Kaikki piirit',
  allSeries: 'Kaikki sarjat',
  allSeriesStartTimesPdf: 'Kaikkien sarjojen lähtöajat (PDF)',
  backToHomePage: 'Takaisin etusivulle',
  backToPage: 'Takaisin sivulle {{pageName}}',
  batchLists: 'Eräluettelot',
  club: 'Seura',
  competitor: 'Kilpailija',
  correctDistances: 'Oikeat etäisyydet',
  cups: 'Cup-kilpailut',
  district: 'Piiri',
  downloadAllResults: 'Lataa tuloskooste',
  downloadBatchList: 'Lataa eräluettelo',
  downloadStartListPdf: 'Lataa lähtölista PDF-tiedostona',
  downloadStartTimes: 'Lataa lähtöajat',
  finalRoundBatchLists: 'Loppukilpailun eräluettelot',
  jotosTeam: 'Jotosjoukkue',
  noCompetitorsOrStartTimes: 'Tähän sarjaan ei ole merkitty kilpailijoita tai heille ei ole määritetty vielä lähtöaikoja.',
  nordic_trap: 'Trap',
  nordic_shotgun: 'Compak',
  nordic_rifle_standing: 'Hirvi',
  nordic_rifle_moving: 'Kauris',
  numberShort: 'Nro',
  pdfPageBreaks: 'Sivunvaihdot sarjojen väliin',
  personalCompetitions: 'Yksilökilpailut',
  press: 'Lehdistö',
  qualificationRoundBatchLists: 'Alkukilpailun eräluettelot',
  raceBeginsIn: 'Kilpailun alkuun on aikaa {{distanceInTime}}',
  raceCancelledMessage: 'Valitettavasti kilpailu on peruttu',
  raceCancelledTitle: 'Kilpailu peruttu',
  raceHomePage: 'Kilpailun kotisivut',
  raceMenuHome: 'Kilpailun etusivu',
  raceOrganizer: 'Kilpailun järjestäjä',
  racePublicMessage: 'Kilpailun järjestäjä tiedottaa',
  raceResultsPdf: 'Tuloskooste (PDF)',
  raceStarted: 'Kilpailu alkoi {{time}}',
  raceStarts: 'Kilpailu alkaa {{time}}',
  raceWithoutSeries: 'Kilpailuun ei ole vielä lisätty sarjoja',
  relays: 'Viestit',
  resultRotation: 'Tuloskehä',
  results: 'Tulokset',
  rifle: 'Luodikko',
  rifleTeamCompetitions: 'Luodikon joukkuekilpailut',
  seriesStartTime: 'Sarjan lähtöaika',
  startList: 'Lähtölista',
  startTime: 'Lähtöaika',
  teamCompetition: 'Joukkuekilpailu',
  teamCompetitions: 'Joukkuekilpailut',
  unofficialCompetitor: 'Epävirallinen kilpailija',
  unofficialShort: 'epäv.',
}
