window.translations = {
  backToPage: 'Takaisin sivulle {{pageName}}',
  club: 'Seura',
  competitor: 'Kilpailija',
  district: 'Piiri',
  downloadStartListPdf: 'Lataa lähtölista PDF-tiedostona',
  jotosTeam: 'Jotosjoukkue',
  noCompetitorsOrStartTimes: 'Tähän sarjaan ei ole merkitty kilpailijoita tai heille ei ole määritetty vielä lähtöaikoja.',
  numberShort: 'Nro',
  press: 'Lehdistö',
  raceMenuHome: 'Kilpailun etusivu',
  relays: 'Viestit',
  resultRotation: 'Tuloskehä',
  results: 'Tulokset',
  seriesStartTime: 'Sarjan lähtöaika',
  startList: 'Lähtölista',
  startTime: 'Lähtöaika',
  teamCompetitions: 'Joukkuekilpailut',
  unofficialCompetitor: 'Epävirallinen kilpailija',
  unofficialShort: 'epäv.',
}
