/* eslint-disable max-len */
window.translations = {
  ageGroupShorterTrip: 'Ikäryhmällä {{ageGroups}} on lyhennetty matka',
  ageGroupsShorterTrip: 'Ikäryhmillä {{ageGroups}} on lyhennetty matka',
  allCompetitors: 'Kaikki kilpailijat',
  allClubs: 'Kaikki seurat',
  allDistricts: 'Kaikki piirit',
  allSeries: 'Kaikki sarjat',
  allSeriesStartTimesPdf: 'Kaikkien sarjojen lähtöajat (PDF)',
  alsoCompetitorsFromClubs: 'Lisäksi kaikki kilpailijat seurasta (paina ctrl, jos haluat valita useita)',
  alsoCompetitorsFromDistricts: 'Lisäksi kaikki kilpailijat piiristä (paina ctrl, jos haluat valita useita)',
  backToCupHomePage: 'Takaisin cup-kilpailun etusivulle',
  backToHomePage: 'Takaisin etusivulle',
  backToPage: 'Takaisin sivulle {{pageName}}',
  batchList: 'Eräluettelo',
  batchListNotCreated: 'Kilpailun eräluetteloa ei ole tehty',
  batchListNotPublished: 'Eräluetteloa ei ole vielä julkaistu',
  club: 'Seura',
  comparisonTime: 'Vertailuaika',
  competitor: 'Kilpailija',
  competitor_DNS: 'Kilpailija ei osallistunut kilpailuun',
  competitor_DNF: 'Kilpailija keskeytti kilpailun',
  competitor_DQ: 'Kilpailija hylättiin',
  competitorsPerSeries: 'Kilpailijoiden määrä / sarja',
  correctDistances: 'Oikeat etäisyydet',
  cupCompetitions: 'Osakilpailut',
  cupHome: 'Cup-kilpailun etusivu',
  cupPointsRule: 'Yhteispisteet lasketaan {{bestCompetitionsCount}} parhaan tuloksen perusteella',
  cupPointsRuleTitle: 'Pistelaskenta',
  cupPointsRuleWithLast: 'Yhteispisteet lasketaan viimeisen kilpailun sekä muista kilpailuista {{bestCompetitionsCount}} parhaan tuloksen perusteella',
  cupPublicMessage: ' Cup-kilpailun järjestäjä tiedottaa',
  cups: 'Cup-kilpailut',
  district: 'Piiri',
  downloadAllResults: 'Lataa tuloskooste',
  downloadBatchList: 'Lataa eräluettelo',
  downloadBatchListPdf: 'Lataa eräluettelo PDF-tiedostona',
  downloadPressReport: 'Lataa lehdistöraportti',
  downloadRelayCompetitorsPdf: 'Lataa osallistujaluettelo PDF-tiedostona',
  downloadResultsPdf: 'Lataa tulokset PDF-tiedostona',
  downloadResultsPdfWithCompetitors: 'Lataa tulos-PDF (kilpailijoiden kanssa)',
  downloadResultsPdfWithoutCompetitors: 'Lataa tulos-PDF (ilman kilpailijoita)',
  downloadStartListPdf: 'Lataa lähtölista PDF-tiedostona',
  downloadStartTimes: 'Lataa lähtöajat',
  estimatePenalties: 'Arviosakot',
  estimating: 'Arviointi',
  european_compak: 'Compak',
  european_rifle: 'Luodikko',
  european_rifle1: 'Metsäkauris',
  european_rifle2: 'Kettu',
  european_rifle3: 'Gemssi',
  european_rifle4: 'Villisika',
  european_trap: 'Trap',
  extraRound: 'Uusinta',
  finalRound: 'Loppukilpailu',
  finalRoundBatchList: 'Loppukilpailun eräluettelo',
  finish: 'Maali',
  hideCompetitors: 'Piilota kilpailijat',
  hideCupCompetitions: 'Piilota osakilpailut',
  hideShots: 'Piilota laukaukset',
  leg: 'Osuus',
  legNumber: 'Osuus {{leg}}',
  legTime: 'Osuusaika',
  name: 'Nimi',
  noCompetitors: 'Ei kilpailijoita',
  noCompetitorsOrStartTimes: 'Tähän sarjaan ei ole lisätty kilpailijoita tai heille ei ole määritetty vielä lähtöaikoja.',
  noCupSeries: 'Cup-sarjoja ei ole vielä määritetty',
  nordic_rifle_moving: 'Hirvi',
  nordic_rifle_standing: 'Kauris',
  nordic_shotgun: 'Compak',
  nordic_trap: 'Trap',
  noTeams: 'Ei joukkueita',
  numberShort: 'Nro',
  pdfPageBreaks: 'Sivunvaihdot sarjojen väliin',
  personalCompetitions: 'Yksilökilpailut',
  points: 'Pisteet',
  press: 'Lehdistö',
  pressInfoUnfinishedRace: 'Tältä sivulta voit ladata lehdistöraportin, kun kilpailu on päättynyt',
  pressReportInstructions: 'Maalaa alla oleva tulosraportti ja kopioi se esimerkiksi sähköpostiisi tai vaikkapa tekstinkäsittelyohjelmaan jatkokäsittelyä varten',
  qualificationRound: 'Alkukilpailu',
  qualificationRoundBatchList: 'Alkukilpailun eräluettelo',
  raceBeginsIn: 'Kilpailun alkuun on aikaa {{distanceInTime}}',
  raceCancelledMessage: 'Valitettavasti kilpailu on peruttu',
  raceCancelledTitle: 'Kilpailu peruttu',
  raceHomePage: 'Kilpailun kotisivut',
  raceMenuHome: 'Kilpailun etusivu',
  raceOrganizer: 'Kilpailun järjestäjä',
  racePublicMessage: 'Kilpailun järjestäjä tiedottaa',
  raceResultsPdf: 'Tuloskooste (PDF)',
  raceStarted: 'Kilpailu alkoi {{time}}',
  raceStarts: 'Kilpailu alkaa {{time}}',
  raceUnfinished: 'Kilpailu on kesken',
  raceUnfinishedDistancesLater: 'Kilpailu on kesken. Tarkemmat arviointitiedot julkaistaan, kun kilpailu on päättynyt.',
  raceWithoutSeries: 'Kilpailuun ei ole vielä lisätty sarjoja',
  relay: 'Viesti',
  relayNotStarted: 'Viesti ei ole vielä alkanut',
  relayPenaltySeconds_RUN: 'Sakkoja ei juosta vaan ne lisätään aikaan. Arviointi: {{estimatePenaltySeconds}} s/sakko. Ammunta: {{shootingPenaltySeconds}} s/sakko.',
  relayPenaltySeconds_SKI: 'Sakkoja ei hiihdetä vaan ne lisätään aikaan. Arviointi: {{estimatePenaltySeconds}} s/sakko. Ammunta: {{shootingPenaltySeconds}} s/sakko.',
  relays: 'Viestit',
  relayStartTime: 'Viestin lähtöaika: {{time}}',
  relayWithoutStartTime: 'Viestin lähtöaikaa ei ole vielä päätetty',
  relayWithoutTeams: 'Viestiin ei ole vielä lisätty joukkueita',
  result: 'Tulos',
  results: 'Tulokset',
  resultsInProgress: 'Tulokset päivitetty {{time}}',
  rifle: 'Luodikko',
  rifleResults: 'Luodikon tulokset',
  rifleTeamCompetition: 'Luodikon joukkuekilpailu',
  rifleTeamCompetitions: 'Luodikon joukkuekilpailut',
  series: 'Sarja',
  seriesShorterTrip: 'Sarjalla on lyhennetty matka',
  seriesNoCompetitors: 'Sarjaan ei ole lisätty kilpailijoita',
  seriesNoStartList: 'Sarjan lähtöluetteloa ei ole vielä julkaistu',
  seriesNotStarted: 'Sarja ei ole vielä alkanut',
  seriesPointsMethod1_SKI: 'Sarjassa on 4 arviota, arviopisteet -1p/1m',
  seriesPointsMethod1_RUN: 'Sarjassa on 4 arviota, arviopisteet -1p/1m',
  seriesPointsMethod2_SKI: 'Hirvenhiihtely (sarjassa on 4 arviota pistein -2p/1m, ei aikapisteitä)',
  seriesPointsMethod2_RUN: 'Hirvikävely (sarjassa on 4 arviota pistein -2p/1m, ei aikapisteitä)',
  seriesPointsMethod3_SKI: 'Hirvenhiihtely (sarjassa on 2 arviota, kaikki saavat 300 aikapistettä)',
  seriesPointsMethod3_RUN: 'Hirvikävely (sarjassa on 2 arviota, kaikki saavat 300 aikapistettä)',
  seriesPointsMethod4_SKI: 'Hirvenhiihtely (sarjassa on 2 arviota pistein -4p/1m, ei aikapisteitä)',
  seriesPointsMethod4_RUN: 'Hirvikävely (sarjassa on 2 arviota pistein -4p/1m, ei aikapisteitä)',
  seriesStartTime: 'Sarjan lähtöaika',
  shooting: 'Ammunta',
  shootingPenalties: 'Ammuntasakot',
  shots: 'Laukaukset',
  showCompetitors: 'Näytä kilpailijat',
  showCupCompetitions: 'Näytä osakilpailut',
  showOfficialResults: 'Näytä viralliset tulokset',
  showShots: 'Näytä laukaukset',
  showUnofficialResults: 'Näytä epäviralliset tulokset (kaikki kilpailijat mukana)',
  startList: 'Lähtölista',
  startLists: 'Lähtölistat',
  startTime: 'Lähtöaika',
  team: 'Joukkue',
  team_DNS: 'Joukkue ei osallistunut kilpailuun',
  team_DNF: 'Joukkue keskeytti kilpailun',
  team_DQ: 'Joukkue hylättiin',
  teamCompetition: 'Joukkuekilpailu',
  teamCompetitions: 'Joukkuekilpailut',
  teamCompetitionResultsNotAvailable: 'Joukkuekilpailun tuloksia ei voida vielä laseka',
  timeTitle_RUN: 'Juoksu',
  timeTitle_SKI: 'Hiihto',
  totalPoints: 'Yhteispisteet',
  track: 'Rata',
  unofficialCompetitor: 'Epävirallinen kilpailija',
  unofficialShort: 'epäv.',
}
