/* eslint-disable max-len */
window.translations = {
  ageGroupShorterTrip: 'Äldsgrupp {{ageGroups}} har kortare löpning',
  ageGroupsShorterTrip: 'Äldsgruppar {{ageGroups}} har kortare löpning',
  allCompetitors: 'All tävlarna',
  allClubs: 'Alla klubber',
  allDistricts: 'Alla trakten',
  allSeries: 'Alla klasser',
  allSeriesStartTimesPdf: 'Starttider för alla klasser (PDF)',
  alsoCompetitorsFromClubs: 'Dessutom alla tävlarna från klubben (tryck ctrl om du vill välja många)',
  alsoCompetitorsFromDistricts: 'Dessutom alla tävlarna från trakten (tryck ctrl om du vill välja många)',
  backToCupHomePage: 'Tillbaka till cup-tävlingens hemsida',
  backToHomePage: 'Tillbaka till hemsida',
  backToPage: 'Tillbaka till sida {{pageName}}',
  batchList: 'Heatlista',
  batchListNotCreated: 'Heatlista är inte färdig',
  batchListNotPublished: 'Heatlista är inte ännu publiserats',
  club: 'Klubb',
  comparisonTime: 'Jämförelsetid',
  competitor: 'Tävlare',
  competitor_DNS: 'Tävlaren startade inte',
  competitor_DNF: 'Tävlaren avbröt',
  competitor_DQ: 'Tävlaren diskad',
  competitorsPerSeries: 'Tävlarna / klass',
  correctDistances: 'Rätta avstånd',
  cupCompetitions: 'Deltävlingar',
  cupHome: 'Cup-tävlingens hemsida',
  cupPointsRule: 'Totalpoäng beräknas på grund av {{bestCompetitionsCount}} bäst resultat',
  cupPointsRuleTitle: 'Poängsberäkning',
  cupPointsRuleWithLast: 'Totalpoäng beräknas på grund av den sista tävlingen och de andra tävlingarnas {{bestCompetitionsCount}} bäst resultat',
  cupPublicMessage: 'Cup-tävlingens organizatör informerar',
  cups: 'Cup-tävlingar',
  district: 'Trakt',
  downloadAllResults: 'Ladda alla resultat',
  downloadBatchList: 'Ladda heatlista',
  downloadBatchListPdf: 'Ladda heatlista som PDF-fil',
  downloadPressReport: 'Ladda pressraporten',
  downloadRelayCompetitorsPdf: 'Ladda startlistan som PDF-fil',
  downloadResultsPdf: 'Ladda resultaten som PDF-fil',
  downloadResultsPdfWithCompetitors: 'Ladda PDF (med tävlarna)',
  downloadResultsPdfWithoutCompetitors: 'Ladda PDF (utan tävlarna)',
  downloadStartListPdf: 'Ladda startlista som PDF-fil',
  downloadStartTimes: 'Ladda starttider',
  estimatePenalties: 'Bedömningsfinar',
  estimating: 'Bedömning',
  european_compak: 'Compak',
  european_rifle: 'Kulskytte',
  european_rifle1: 'Rådjur',
  european_rifle2: 'Räv',
  european_rifle3: 'Gems',
  european_rifle4: 'Vildsvin',
  european_trap: 'Trap',
  extraRound: 'Omskjutning',
  finalRound: 'Final',
  finalRoundBatchList: 'Finalens heatlista',
  finish: 'Mål',
  hideCompetitors: 'Gömma tävlarna',
  hideCupCompetitions: 'Gömma deltävlingar',
  hideShots: 'Gömma skott',
  leg: 'Sträcka',
  legNumber: 'Sträcka {{leg}}',
  legTime: 'Sträckatid',
  name: 'Namn',
  noCompetitors: 'Inga tävlar',
  noCompetitorsOrStartTimes: 'Denna klassen här inga tävlar eller dom har inga starttider ännu.',
  noCupSeries: 'Cup-sarjoja ei ole vielä määritetty',
  nordic_rifle_moving: 'Älg',
  nordic_rifle_standing: 'Rådjur',
  nordic_shotgun: 'Compak',
  nordic_trap: 'Trap',
  noTeams: 'Inga lag',
  numberShort: 'Nr',
  pdfPageBreaks: 'Sidbytningar mellan klasserna',
  personalCompetitions: 'Normaltävlingar',
  points: 'Poäng',
  press: 'Press',
  pressInfoUnfinishedRace: 'På den här sidan kan du hämta pressraporten, när tävlingen har slutats',
  pressReportInstructions: 'Dun kan kopiera resultraporten nedenför och bifoga den till exempel till din epost',
  qualificationRound: 'Grundtävling',
  qualificationRoundBatchList: 'Grundtävlingens heatlista',
  raceBeginsIn: 'Tävlingen börjar om {{distanceInTime}}',
  raceCancelledMessage: 'Tyvärr tävlingen är inställd',
  raceCancelledTitle: 'Tävlingen inställd',
  raceHomePage: 'Tävlingens hemsidor',
  raceMenuHome: 'Tävlingens hemsida',
  raceOrganizer: 'Tävlingens organizatör',
  racePublicMessage: 'Tävlingens organizatör informerar',
  raceResultsPdf: 'Alla resultat (PDF)',
  raceStarted: 'Tävlingen började {{time}}',
  raceStarts: 'Tävlingen börjar {{time}}',
  raceUnfinished: 'Tävlingen ofärdig',
  raceUnfinishedDistancesLater: 'Tävlingen ofärdig. Precis avståndsdata publiseras, när tävlingen har slutat.',
  raceWithoutSeries: 'Tävlingen saknas klasser för tillfället',
  relay: 'Stafett',
  relayNotStarted: 'Stafetten har inte ännu börjat',
  relayPenaltySeconds_RUN: 'Sakkoja ei juosta vaan ne lisätään aikaan. Arviointi: {{estimatePenaltySeconds}} s/sakko. Ammunta: {{shootingPenaltySeconds}} s/sakko.',
  relayPenaltySeconds_SKI: 'Sakkoja ei hiihdetä vaan ne lisätään aikaan. Arviointi: {{estimatePenaltySeconds}} s/sakko. Ammunta: {{shootingPenaltySeconds}} s/sakko.',
  relays: 'Stafetter',
  relayStartTime: 'Stafettens starttid: {{time}}',
  relayWithoutStartTime: 'Stafetten har inte ännu starttid',
  relayWithoutTeams: 'Inga lagen tillsatt för stafetten ännu',
  result: 'Resultat',
  resultRotation: 'Resultatskrets',
  resultRotationInfo: 'Välj åtminstone två klasser och starta resultatskrets. När du vill stoppa kretsen, kom tillbaka på den här sidan.',
  resultRotationStart: 'Starta resultatskrets',
  resultRotationStop: 'Stoppa resultatskrets',
  results: 'Resultat',
  resultsInProgress: 'Resultat updaterad {{time}}',
  rifle: 'Kulskytte',
  rifleResults: 'Kulskyttes resultat',
  rifleTeamCompetition: 'Kulskyttes lagtävling',
  rifleTeamCompetitions: 'Kulskyttes lagtävlingar',
  secondsPerPage: 'Sekunder / sida',
  series: 'Klass',
  seriesPlural: 'Klasser',
  seriesShorterTrip: 'Klassen har kortare löpning',
  seriesNoCompetitors: 'Inga tävlar i klassen',
  seriesNoStartList: 'Klassens startlist har inte ännu publiserats',
  seriesNotStarted: 'Klassen har inte ännu börjat',
  seriesPointsMethod1_SKI: '4 bedömningar, -1p/1m',
  seriesPointsMethod1_RUN: '4 bedömningar, -1p/1m',
  seriesPointsMethod2_SKI: '4 bedömningar, inga tidpoäng',
  seriesPointsMethod2_RUN: '4 bedömningar, inga tidpoäng',
  seriesPointsMethod3_SKI: '2 bedömningar, alla tävlarna får 300 tidpoäng',
  seriesPointsMethod3_RUN: '2 bedömningar, alla tävlarna får 300 tidpoäng',
  seriesPointsMethod4_SKI: '2 bedömningar, inga tidpoäng',
  seriesPointsMethod4_RUN: '2 bedömningar, inga tidpoäng',
  seriesStartTime: 'Klassens starttid',
  shooting: 'Skytte',
  shootingPenalties: 'Skyttefinar',
  shots: 'Skott',
  showCompetitors: 'Visa tävlarna',
  showCupCompetitions: 'Visa deltävlingar',
  showOfficialResults: 'Visa formella resultaten',
  showShots: 'Visa skott',
  showUnofficialResults: 'Visa informella resultaten (inkl. all tävlarna)',
  startList: 'Startlista',
  startLists: 'Startlista',
  startTime: 'Starttid',
  team: 'Lag',
  team_DNS: 'Laget startade inte',
  team_DNF: 'Laget avbröt',
  team_DQ: 'Laget diskad',
  teamCompetitionResultsNotAvailable: 'Lagtävlingens resultat kan inte beräknas ännu',
  teamCompetition: 'Lagtävling',
  teamCompetitions: 'Lagtävlingar',
  timeTitle_RUN: 'Löpning',
  timeTitle_SKI: 'Skidning',
  totalPoints: 'Totalpoäng',
  track: 'Bana',
  unofficialCompetitor: 'Informella tävlare',
  unofficialShort: 'inf.',
}
