window.translations = {
  allClubs: 'Alla klubber',
  allDistricts: 'Alla trakten',
  allSeries: 'Alla klasser',
  allSeriesStartTimesPdf: 'Starttider för alla klasser (PDF)',
  backToHomePage: 'Tillbaka till hemsida',
  backToPage: 'Tillbaka till sida {{pageName}}',
  batchLists: 'Heatlista',
  club: 'Klubb',
  competitor: 'Tävlare',
  correctDistances: 'Rätta avstånd',
  cups: 'Cup-tävlingar',
  district: 'Trakt',
  downloadAllResults: 'Ladda alla resultat',
  downloadBatchList: 'Ladda heatlista',
  downloadStartListPdf: 'Ladda startlista som PDF-fil',
  downloadStartTimes: 'Ladda starttider',
  finalRoundBatchLists: 'Finalens heatlista',
  jotosTeam: 'Jotos-lag',
  noCompetitorsOrStartTimes: 'Denna klassen här inga tävlar eller dom har inga starttider ännu.',
  nordic_rifle_moving: 'Rådjur',
  nordic_rifle_standing: 'Älg',
  nordic_shotgun: 'Compak',
  nordic_trap: 'Trap',
  numberShort: 'Nr',
  pdfPageBreaks: 'Sidbytningar mellan klasserna',
  personalCompetitions: 'Normaltävlingar',
  press: 'Press',
  qualificationRoundBatchLists: 'Grundtävlingens heatlista',
  raceBeginsIn: 'Tävlingen börjar om {{distanceInTime}}',
  raceCancelledMessage: 'Tyvärr tävlingen är inställd',
  raceCancelledTitle: 'Tävlingen inställd',
  raceHomePage: 'Tävlingens hemsidor',
  raceMenuHome: 'Tävlingens hemsida',
  raceOrganizer: 'Tävlingens organizatör',
  racePublicMessage: 'Tävlingens organizatör informerar',
  raceResultsPdf: 'Alla resultat (PDF)',
  raceStarted: 'Tävlingen började {{time}}',
  raceStarts: 'Tävlingen börjar {{time}}',
  raceWithoutSeries: 'Tävlingen saknas klasser för tillfället',
  relays: 'Stafett',
  resultRotation: 'Resultatskrets',
  results: 'Resultat',
  rifle: 'Kulskytte',
  rifleTeamCompetitions: 'Kulskyttes lagtävlingar',
  seriesStartTime: 'Klassens starttid',
  startList: 'Startlista',
  startTime: 'Starttid',
  teamCompetition: 'Lagtävling',
  teamCompetitions: 'Lagtävlingar',
  unofficialCompetitor: 'Informella tävlare',
  unofficialShort: 'inf.',
}
