/* eslint-disable max-len */
window.officialTranslations = {
  add: 'Lisää',
  backToOfficialRacePage: 'Takaisin Yhteenveto-sivulle',
  cancel: 'Peruuta',
  clubsPageInfo: 'Tällä sivulla voit lisätä kilpailuun osallistuvien kilpailijoiden seuroja/piirejä sekä korjata niiden nimiä ja poistaa ylimääräisiä. Huom! Voit lisätä seuroja/piirejä myös samalla, kun lisäät kilpailijoita.',
  clubsPageCompetitorsCount: '{{count}} kilpailijaa',
  clubsLongNameInfo: 'Käytetään joukkuekilpailuissa, jos syötetty',
  edit: 'Muokkaa',
  longName: 'Pitkä nimi',
  megaLinkImportTitle: 'Megalink-tulokset',
  megaLinkImportFile: 'Tiedoston sisältö',
  megaLinkImportContentsError: 'Tiedoston sisältö on virheellinen',
  megaLinkImportSuccess: 'Tulokset tallennettu',
  officialRaceMenuHome: 'Yhteenveto',
  officialRaceMenuEdit: 'Perustiedot',
  officialRaceMenuCompetitors: 'Kilpailijat',
  officialRaceMenuStartList: 'Lähtöajat',
  officialRaceMenuBatchListGeneration: 'Erien arvonta',
  officialRaceMenuQualificationRoundBatchList: 'Alkukilpailu',
  officialRaceMenuFinalRoundBatchList: 'Loppukilpailu',
  officialRaceMenuBatches: 'Erät',
  officialRaceMenuQuickSave: 'Pikasyöttö',
  officialRaceMenuTimes: 'Ajat',
  officialRaceMenuEstimates: 'Arviot',
  officialRaceMenuShooting: 'Ammunta',
  officialRaceMenuShootingBySeries: 'Ammunta sarjoittain',
  officialRaceMenuShootingByBatches: 'Ammunta erittäin',
  officialRaceMenuCorrectDistances: 'Oikeat etäisyydet',
  officialRaceMenuCsv: 'CSV',
  officialRaceMenuTeamCompetitions: 'Joukkuek.',
  officialRaceMenuRelays: 'Viestit',
  officialRaceMenuOfficials: 'Toimitsijat',
  officialsCountMany: '{{count}} toimitsijaa',
  officialsCountOne: '1 toimitsija',
  save: 'Tallenna',
}
