/* eslint-disable max-len */
window.officialTranslations = {
  add: 'Öka',
  backToOfficialRacePage: 'Tillbaka till Sammanfattning-sida',
  clubsPageInfo: 'På den här sidan kan du öka klubbar och radera önodiga. Obs! Du kan öka klubbar också när du ökar tävlar.',
  clubsPageCompetitorsCount: '{{count}} tävlar',
  officialRaceMenuHome: 'Sammanfattning',
  officialRaceMenuEdit: 'Basinformation',
  officialRaceMenuCompetitors: 'Tävlar',
  officialRaceMenuStartList: 'Starttider',
  officialRaceMenuBatchListGeneration: 'Heatlotteri',
  officialRaceMenuQualificationRoundBatchList: 'Grundtävling',
  officialRaceMenuFinalRoundBatchList: 'Final',
  officialRaceMenuBatches: 'Heat',
  officialRaceMenuQuickSave: 'Resultat',
  officialRaceMenuTimes: 'Tider',
  officialRaceMenuEstimates: 'Bedömning',
  officialRaceMenuShooting: 'Skytte',
  officialRaceMenuShootingBySeries: 'Skytte (klasser)',
  officialRaceMenuShootingByBatches: 'Skytte (heat)',
  officialRaceMenuCorrectDistances: 'Riktiga avstånd',
  officialRaceMenuCsv: 'CSV',
  officialRaceMenuTeamCompetitions: 'Lagtävlingar',
  officialRaceMenuRelays: 'Stafetter',
  officialRaceMenuOfficials: 'Funktionärer',
}
