window.officialTranslations = {
  add: 'Lisää',
  addCompetitorsFromCsvFile: 'Lisää kilpailijoita CSV-tiedostosta',
  addManyOfficials: 'Lisää monta toimitsijaa',
  addOfficial: 'Lisää toimitsija',
  ageGroup: 'Ikäryhmä',
  ageGroupShooting: 'Aliryhmä',
  allTens: 'Kaikki kymppejä',
  arrivalTime: 'Saapumisaika',
  backToOfficialEventPage: 'Takaisin tapahtuman etusivulle',
  backToOfficialIndexPage: 'Takaisin toimitsijan etusivulle',
  backToOfficialRacePage: 'Takaisin Yhteenveto-sivulle',
  backToOfficialSeriesPage: 'Takaisin sarjan {{seriesName}} kilpailijaluetteloon',
  cancel: 'Peruuta',
  clubsPageInfo:
    'Tällä sivulla voit lisätä kilpailuun osallistuvien kilpailijoiden seuroja/piirejä sekä korjata niiden nimiä ja poistaa ylimääräisiä. Huom! Voit lisätä seuroja/piirejä myös samalla, kun lisäät kilpailijoita.',
  clubsPageCompetitorsCount: '{{count}} kilpailijaa',
  clubsLongNameInfo: 'Käytetään joukkuekilpailuissa, jos syötetty',
  competitorNumbersSync: 'Synkronoi kilpailijanumerot',
  competitorNumbersSyncConfirm:
    'Ymmärrän, että toiminto muuttaa kilpailijoiden numeroita alla olevissa kilpailuissa eikä vanhaa tilaa voi palauttaa',
  competitorNumbersSyncDone: 'Kilpailijanumerot synkronoitu',
  competitorNumbersSyncInfo: 'Tällä sivulla voit synkronoida tapahtuman kilpailuiden kilpailijanumerot.',
  competitorNumbersSyncInvalidRaces: 'Toiminto ei ole saatavilla tapahtumille, joissa on mukana liikuntalajeja.',
  competitorNumbersSyncRaceStarted: 'Toimintoa ei voi enää käyttää, koska kilpailut ovat alkaneet.',
  deleteCompetitor: 'Poista kilpailija',
  deleteCompetitorConfirmation: 'Haluatko varmasti poistaa tämän kilpailijan?',
  edit: 'Muokkaa',
  editCompetitor: 'Muokkaa kilpailijan tietoja',
  editOfficialRights: 'Muokkaa toimitsijan oikeuksia',
  eitherTotalScoreOrShots: 'Syötä joko yhteistulos TAI yksittäiset laukaukset, ei molempia',
  estimate: 'Arvio',
  europeanCompakScoreInput: 'Compakin tulos',
  europeanCompakShots: 'Compakin laukaukset',
  europeanExtraScore: 'Yhdistelmäkilpailun uusinnan yhteistulos',
  europeanRifle1ScoreInput: 'Metsäkauriin tulos',
  europeanRifle1Shots: 'Metsäkauriin laukaukset',
  europeanRifle2ScoreInput: 'Ketun tulos',
  europeanRifle2Shots: 'Ketun laukaukset',
  europeanRifle3ScoreInput: 'Gemssin tulos',
  europeanRifle3Shots: 'Gemssin laukaukset',
  europeanRifle4ScoreInput: 'Villisian tulos',
  europeanRifle4Shots: 'Villisian laukaukset',
  europeanRifleExtraShots: 'Luodikon uusintalaukaukset',
  europeanShotgunExtraScore: 'Haulikon uusinta',
  europeanTrapScoreInput: 'Trapin tulos',
  europeanTrapShots: 'Trapin laukaukset',
  extraRound: 'Uusinta',
  eventEdit: 'Muokkaa tapahtumaa',
  eventPrintCompetitorOptions: 'Lisäasetukset',
  eventPrintCompetitorOrder: 'Kilpailijoiden järjestys',
  eventPrintCompetitorOrder_alphabetical: 'Aakkosjärjestys',
  eventPrintCompetitorOrder_clubAlphabetical: 'Aakkosjärjestys piireittäin',
  eventPrintCompetitorOrder_clubNumbers: 'Numerojärjestys piireittäin',
  eventPrintCompetitorOrder_numbers: 'Numerojärjestys',
  eventPrintCompetitorType: 'Tulosteen muoto',
  eventPrintCompetitorType_numbers: 'Numerolaput',
  eventPrintCompetitorType_list: 'Luettelo',
  eventPrintCompetitorWithRaces: 'Tulosta lajit ja sarjat',
  eventRaces: 'Tapahtumaan kuuluvat kilpailut',
  eventsAtLeastTwoRaces:
    'Sinulla pitää olla vähintään kaksi kilpailua, jotta voit luoda tapahtuman. Kilpailu voi kuulua vain yhteen tapahtumaan.',
  eventsNew: 'Uusi tapahtuma',
  extraShots: 'Uusinnan laukaukset',
  firstName: 'Etunimi',
  firstNumber: 'Ensimmäinen numero',
  finalRoundHeat: 'Loppukilpailun erä',
  finalRoundShootingScoreInput: 'Loppukilpailun yhteistulos',
  finalRoundShots: 'Loppukilpailun laukaukset',
  finalRoundTrackPlace: 'Loppukilpailun ratapaikka',
  generateStartTimes: 'Lähtöaikojen ja -numeroiden luonti',
  lastName: 'Sukunimi',
  longName: 'Pitkä nimi',
  megaLinkImportTitle: 'Megalink-tulokset',
  megaLinkImportFile: 'Tiedoston sisältö',
  megaLinkImportContentsError: 'Tiedoston sisältö on virheellinen',
  megaLinkImportSuccess: 'Tulokset tallennettu',
  nordicRifleMovingExtraShots: 'Liikkuvan hirven uusintalaukaukset',
  nordicRifleMovingScoreInput: 'Liikkuvan hirven tulos',
  nordicRifleMovingShots: 'Liikkuvan hirven laukaukset',
  nordicRifleStandingExtraShots: 'Seisovan kauriin uusintalaukaukset',
  nordicRifleStandingScoreInput: 'Seisovan kauriin tulos',
  nordicRifleStandingShots: 'Seisovan kauriin laukaukset',
  nordicShotgunExtraShots: 'Compakin uusintalaukaukset',
  nordicShotgunScoreInput: 'Compakin tulos',
  nordicShotgunShots: 'Compakin laukaukset',
  nordicTrapExtraShots: 'Trapin uusintalaukaukset',
  nordicTrapScoreInput: 'Trapin tulos',
  nordicTrapShots: 'Trapin laukaukset',
  noResultReason: 'Tila',
  officialEventMenuCompetitors: 'Kilpailijat',
  officialEventMenuHome: 'Yhteenveto',
  officialEventMenuPrints: 'Kilpailijoiden tulostus',
  officialEventMenuSyncNumbers: 'Synkronoi numerot',
  officialPageAddManyDescription:
    'Tällä sivulla voit kutsua monta toimitsijaa kerralla. Listaa toimitsijoiden sähköpostiosoitteet ja jos haluat heille rajoitetut oikeudet, lisää perään piiri / seura alla olevan esimerkin mukaisesti. Henkilöiden täytyy olla rekisteröitynyt palveluun omilla sähköpostiosoitteillaan.',
  officialPageAddManyTitle: 'Kutsu monta toimitsijaa kilpailun toimitsijoiksi',
  officialPageAllCurrent: 'Kaikki nykyiset',
  officialPageAllowAddingClubs: 'Salli uusien piirien/seurojen lisäys',
  officialPageAllowSpecificClub: 'Salli kilpailijoiden lisäys vain tiettyyn piiriin/seuraan',
  officialPageAddingAllowed: 'Lisäys sallittu',
  officialPageCancelInvitation: 'Peruuta kutsu',
  officialPageCannotLimitUsagePre: 'Käyttöä ei voi rajata, koska',
  officialPageCannotLimitUsagePost: 'yhtään piiriä/seuraa ei ole lisätty',
  officialPageDeleteRightsConfirmation: 'Haluatko varmasti poistaa käyttäjän toimitsijaoikeudet tähän kilpailuun?',
  officialPageEmailsAndClubs: 'Sähköpostit ja mahdolliset piirit/seurat',
  officialPageFullRights: 'Täydet oikeudet',
  officialPageInvite: 'Kutsu toinen henkilö tämän kilpailun toimitsijaksi',
  officialPageNoLimitation: 'Ei rajausta',
  officialPageOnlyAddCompetitors: 'Anna käyttäjälle ainoastaan oikeudet lisätä kilpailijoita',
  officialPagePendingInvites: 'Odottaa rekisteröitymistä',
  officialPageRaceOfficials: 'Kilpailun toimitsijat',
  officialPageRequirement: 'Henkilön täytyy olla rekisteröitynyt palveluun omalla sähköpostiosoitteellaan.',
  officialPageSendInvitation: 'Lähetä kutsu',
  officialPageSendInvitations: 'Lähetä kutsut',
  officialRaceMenuHome: 'Yhteenveto',
  officialRaceMenuEdit: 'Perustiedot',
  officialRaceMenuCompetitors: 'Kilpailijat',
  officialRaceMenuStartList: 'Lähtöajat',
  officialRaceMenuHeatListGeneration: 'Erien arvonta',
  officialRaceMenuQualificationRoundHeatList: 'Alkukilpailu',
  officialRaceMenuFinalRoundHeatList: 'Loppukilpailu',
  officialRaceMenuHeats: 'Erät',
  officialRaceMenuQuickSave: 'Pikasyöttö',
  officialRaceMenuTimes: 'Ajat',
  officialRaceMenuEstimates: 'Arviot',
  officialRaceMenuShooting: 'Ammunta',
  officialRaceMenuShootingBySeries: 'Ammunta sarjoittain',
  officialRaceMenuShootingByHeats: 'Ammunta erittäin',
  officialRaceMenuCorrectDistances: 'Oikeat etäisyydet',
  officialRaceMenuCsv: 'CSV',
  officialRaceMenuTeamCompetitions: 'Joukkuek.',
  officialRaceMenuRelays: 'Viestit',
  officialRaceMenuOfficials: 'Toimitsijat',
  officialsCountMany: '{{count}} toimitsijaa',
  officialsCountOne: '1 toimitsija',
  onlyRifle: 'Osallistuu vain luodikkoon',
  printPdf: 'Tulosta PDF',
  qualificationRoundHeat: 'Alkukilpailun erä',
  qualificationRoundShootingScoreInput: 'Alkukilpailun yhteistulos',
  qualificationRoundShots: 'Alkukilpailun laukaukset',
  qualificationRoundTrackPlace: 'Alkukilpailun ratapaikka',
  newClub: 'Uusi {{clubLabel}}',
  newCompetitor: 'Uusi kilpailija',
  noCompetitorsInHeat: 'Erässä ei ole yhtään kilpailijaa',
  noCompetitorsInRace: 'Et ole syöttänyt kilpailuun vielä yhtään kilpailijaa.',
  noCompetitorsInSeries: 'Et ole syöttänyt tähän sarjaan vielä yhtään kilpailijaa.',
  noHeats: 'Yhtään erää ei ole vielä määritetty',
  noStartListForSeries:
    'Tähän sarjaan ei ole luotu vielä lähtölistaa. Tulokset voi syöttää vasta sitten kun lähtölista on luotu.',
  number: 'Numero',
  recentlyAddedCompetitors: 'Viimeksi lisätyt kilpailijat',
  save: 'Tallenna',
  saveAndShowCompetitor: 'Tallenna ja näytä kilpailija',
  saveAndToQuickSave: 'Tallenna ja siirry tulosten pikasyöttöön',
  saved: 'Tallennettu',
  selectAll: 'Valitse kaikki',
  selectClubOrAddNew: 'Valitse {{clubLabel}} tai lisää uusi',
  selectHeat: 'Valitse erä',
  shootingScoreInput: 'Ammunta yhteensä',
  shootingRulesPenalty: 'Rangaistus ammuntasääntöjen rikkomisesta',
  shootingRulesPenaltyFinal: 'Rangaistus ammuntasääntöjen rikkomisesta loppukilpailussa',
  shootingRulesPenaltyQr: 'Rangaistus ammuntasääntöjen rikkomisesta alkukilpailussa',
  shotsPageSortByNumber: 'Järjestä kilpailijat numerojärjestykseen',
  shotsPageSortByQR: 'Järjestä kilpailijat alkukilpailun tulosten mukaan',
  trackPlace: 'Ratapaikka',
  unofficial: 'Epävirallinen kilpailija',
  update: 'Päivitä',
}
