window.officialTranslations = {
  add: 'Lägg till',
  addCompetitorsFromCsvFile: 'Lägg till tävlande från CSV-fil',
  added: 'Tillagt',
  addNew: 'Lägg till',
  addNewClub: 'Lägg till ny {{clubLabel}}',
  addManyOfficials: 'Lägg till många funktionärer',
  addOfficial: 'Lägg till funktionär',
  ageGroup: 'Åldersgrupp',
  ageGroupShooting: 'Grupp',
  allTens: '10 för alla',
  arrivalTime: 'Ankomstid',
  backToOfficialEventPage: 'Tillbaka till evenemangets sammanfattningnssida',
  backToOfficialIndexPage: 'Tillbaka till funktionärens hemsida',
  backToOfficialRacePage: 'Tillbaka till sammanfattningnssidan',
  backToOfficialSeriesPage: 'Tillbaka till klassens {{seriesName}} tävlandelist',
  cancel: 'Avbryt',
  clubsPageInfo:
    'På den här sidan kan du lägga till klubbar och radera onödiga. Obs! Du kan också lägga till klubbar när du lägger till tävlande.',
  clubsPageCompetitorsCount: '{{count}} tävlande',
  clubsLongNameInfo: 'Används i lagtävlingar om det anges',
  competitorNumbersSync: 'Synkronisera nummer',
  competitorNumbersSyncConfirm:
    'Jag förstår att funktionen ändrar tävlandes nummer i tävlingarna nedan och att det gamla läget inte kan återställas',
  competitorNumbersSyncDone: 'Tävlingsnummer synkroniserade',
  competitorNumbersSyncInfo: 'På den här sidan kan du synkronisera tävlingsnummer inom evenemanget.',
  competitorNumbersSyncInvalidRaces:
    'Funktionen är inte tillgänglig för evenemang som innehåller älgskidskytte eller älglöpning',
  competitorNumbersSyncRaceStarted: 'Funktionen kan inte längre användas eftersom tävlingarna har startat.',
  deleteCompetitor: 'Radera tävlande',
  deleteCompetitorConfirmation: 'Är du säker att du vill radera tävlande?',
  edit: 'Redigera',
  editCompetitor: 'Redigera tävlande',
  editOfficialRights: 'Redigera funktionärens rättigheter',
  eitherTotalScoreOrShots: 'Spara antingen totalresultat eller enskilda skott, inte båda',
  estimate: 'Bedömning',
  europeanCompakScoreInput: 'Compak resultat',
  europeanCompakShots: 'Compak skott',
  europeanExtraScore: 'Kombinationstävlingens omskjutningsresultat',
  europeanRifle1ScoreInput: 'Rådjur resultat',
  europeanRifle1Shots: 'Rådjur skott',
  europeanRifle2ScoreInput: 'Räv skott',
  europeanRifle2Shots: 'Räv resultat',
  europeanRifle3ScoreInput: 'Gems resultat',
  europeanRifle3Shots: 'Gems skott',
  europeanRifle4ScoreInput: 'Vildsvin resultat',
  europeanRifle4Shots: 'Vildsvin skott',
  europeanRifleExtraShots: 'Kulskytte omskjutning',
  europeanShotgunExtraScore: 'Compak och trap omskjutning',
  europeanTrapScoreInput: 'Jägartrap resultat',
  europeanTrapShots: 'Jägartrap skott',
  extraRound: 'Omskjutning',
  eventEdit: 'Redigera evenemanget',
  eventPrintCompetitorOptions: 'Ytterligare alternativ',
  eventPrintCompetitorOrder: 'Tävlarnas ordnung',
  eventPrintCompetitorOrder_alphabetical: 'Alfabetisk ordning',
  eventPrintCompetitorOrder_clubAlphabetical: 'Alfabetisk ordning efter distrikt',
  eventPrintCompetitorOrder_clubNumbers: 'Nummerordning efter distrikt',
  eventPrintCompetitorOrder_numbers: 'Nummerordning',
  eventPrintCompetitorType: 'Utskriftens format',
  eventPrintCompetitorType_numbers: 'Nummerlappar',
  eventPrintCompetitorType_list: 'Lista',
  eventPrintCompetitorWithRaces: 'Inkludera grenerna och klasserna',
  eventRaces: 'Tävlingarna som hör till evenemanget',
  eventsAtLeastTwoRaces:
    'Du måste ha minst två tävlingar för att kunna skapa ett evenemang. En tävling kan endast höra till ett evenemang.',
  eventsNew: 'Nytt evenemang',
  extraShots: 'Omskjutning',
  firstName: 'Förnamn',
  firstNumber: 'Första numret',
  finalRoundHeat: 'Finalens heat',
  finalRoundShootingScoreInput: 'Finalens resultat',
  finalRoundShots: 'Finalens skott',
  finalRoundTrackPlace: 'Finalens plats',
  generateStartTimes: 'Skapa starttider och -nummer',
  lastName: 'Efternamn',
  longName: 'Långt namn',
  megaLinkImportTitle: 'Megalink-resultat',
  megaLinkImportFile: 'Fil',
  megaLinkImportContentsError: 'Filen har fel format',
  megaLinkImportSuccess: 'Resultaten sparats',
  nordicRifleMovingExtraShots: 'Älg omskjutning',
  nordicRifleMovingScoreInput: 'Älg resultat',
  nordicRifleMovingShots: 'Älg skott',
  nordicRifleStandingExtraShots: 'Rådjur omskjutning',
  nordicRifleStandingScoreInput: 'Rådjur resultat',
  nordicRifleStandingShots: 'Rådjur skott',
  nordicShotgunExtraShots: 'Compak omskjutning',
  nordicShotgunScoreInput: 'Compak resultat',
  nordicShotgunShots: 'Compak skott',
  nordicTrapExtraShots: 'Jägartrap omskjutning',
  nordicTrapScoreInput: 'Jägartrap resultat',
  nordicTrapShots: 'Jägartrap skott',
  noResultReason: 'Status',
  officialEventMenuCompetitors: 'Tävlande',
  officialEventMenuHome: 'Sammanfattning',
  officialEventMenuPrints: 'Utskrift',
  officialEventMenuSyncNumbers: 'Synkronisera nummer',
  officialPageAddManyDescription:
    'På den här sidan kan du bjuda in flera funktionärer samtidigt. Lista funktionärernas e-postadresser och om du vill ge dem begränsade rättigheter, lägg till distrikt / förening efter exemplet nedan. Personerna måste vara registrerade i tjänsten med sina egna e-postadresser.',
  officialPageAddManyTitle: 'Bjud in flera funktionärer till tävlingens funktionärer',
  officialPageAllCurrent: 'Alla aktuella',
  officialPageAllowAddingClubs: 'Tillåt att lägga till nya trakt/klubbar',
  officialPageAllowSpecificClub: 'Tillåt att lägga till deltagare endast till ett specifikt traktet/klubban',
  officialPageAddingAllowed: 'Tillägg tillåtet',
  officialPageCancelInvitation: 'Avbryt inbjudan',
  officialPageCannotLimitUsagePre: 'Användningen kan inte begränsas eftersom',
  officialPageCannotLimitUsagePost: 'ingen trakt/klubb har lagts till',
  officialPageDeleteRightsConfirmation:
    'Vill du verkligen ta bort användarens funktionärsrättigheter för denna tävling?',
  officialPageEmailsAndClubs: 'E-postadresser och eventuella trakt/klubbar',
  officialPageFullRights: 'Fullständiga rättigheter',
  officialPageInvite: 'Bjud in en annan person som funktionär till denna tävling',
  officialPageNoLimitation: 'Ingen begränsning',
  officialPageOnlyAddCompetitors: 'Ge användaren endast rättigheter att lägga till deltagare',
  officialPagePendingInvites: 'Väntar på registrering',
  officialPageRaceOfficials: 'Tävlingens funktionärer',
  officialPageRequirement: 'Personen måste vara registrerad på tjänsten med sin egen e-postadress.',
  officialPageSendInvitation: 'Skicka inbjudan',
  officialPageSendInvitations: 'Skicka inbjudningar',
  officialRaceMenuHome: 'Sammanfattning',
  officialRaceMenuEdit: 'Basinformation',
  officialRaceMenuCompetitors: 'Tävlande',
  officialRaceMenuStartList: 'Starttider',
  officialRaceMenuHeatListGeneration: 'Lottning av heat',
  officialRaceMenuQualificationRoundHeatList: 'Grundtävling',
  officialRaceMenuFinalRoundHeatList: 'Final',
  officialRaceMenuHeats: 'Heat',
  officialRaceMenuQuickSave: 'Resultat',
  officialRaceMenuTimes: 'Tider',
  officialRaceMenuEstimates: 'Bedömning',
  officialRaceMenuShooting: 'Skytte',
  officialRaceMenuShootingBySeries: 'Skytte (klasser)',
  officialRaceMenuShootingByHeats: 'Skytte (heat)',
  officialRaceMenuCorrectDistances: 'Riktiga avstånd',
  officialRaceMenuCsv: 'CSV',
  officialRaceMenuTeamCompetitions: 'Lagtävlingar',
  officialRaceMenuRelays: 'Stafetter',
  officialRaceMenuOfficials: 'Funktionärer',
  officialsCountMany: '{{count}} funktionärer',
  officialsCountOne: '1 funktionär',
  onlyRifle: 'Deltagar bara kulskytte',
  printPdf: 'Skriv ut PDF',
  qualificationRoundHeat: 'Grundtävlingens heat',
  qualificationRoundShootingScoreInput: 'Grundtävlingens resultat',
  qualificationRoundShots: 'Grundtävlingens skott',
  qualificationRoundTrackPlace: 'Grundtävlingens plats',
  newClub: 'Ny {{clubLabel}}',
  newCompetitor: 'Ny tävlande',
  noCompetitorsInHeat: 'Heatet har inga tävlande',
  noCompetitorsInRace: 'Du har sparat inga tävlande för tävlingen.',
  noCompetitorsInSeries: 'Du har sparat inga tävlande för den här klassen.',
  noHeats: 'Det finns inga heat',
  noStartListForAnySeries: 'Ingen klass har startlist ännu',
  noStartListForSeries:
    'Den här klassen har inte ännu startlista. Du kan spara resultat efter startlistan har skapats.',
  number: 'Nummer',
  recentlyAddedCompetitors: 'Senaste ökade tävlande',
  save: 'Spara',
  saveAndShowCompetitor: 'Spara och visa tävlande',
  saveAndToQuickSave: 'Spara och gå till resultatsidan',
  saved: 'Sparat',
  selectAll: 'Välj alla',
  selectClubOrAddNew: 'Välj {{clubLabel}} eller lägg till en ny',
  selectHeat: 'Välj heat',
  shootingScoreInput: 'Skottstotal',
  shootingRulesPenalty: 'Straff för brott mot skjutregler',
  shootingRulesPenaltyFinal: 'Straff för brott mot skjutregler i finalen',
  shootingRulesPenaltyQr: 'Straff för brott mot skjutregler i grundtävlingen',
  shotsPageSortByNumber: 'Ordna normalt',
  shotsPageSortByQR: 'Ordna tävlandeana på grund av grundtävlingens resultat',
  trackPlace: 'Bana',
  unofficial: 'Informella tävlande',
  update: 'Uppdatera',
}
