/* eslint-disable max-len */
window.officialTranslations = {
  add: 'Lisää',
  addManyOfficials: 'Lisää monta toimitsijaa',
  addOfficial: 'Lisää toimitsija',
  backToOfficialIndexPage: 'Takaisin toimitsijan etusivulle',
  backToOfficialRacePage: 'Takaisin Yhteenveto-sivulle',
  cancel: 'Peruuta',
  clubsPageInfo: 'Tällä sivulla voit lisätä kilpailuun osallistuvien kilpailijoiden seuroja/piirejä sekä korjata niiden nimiä ja poistaa ylimääräisiä. Huom! Voit lisätä seuroja/piirejä myös samalla, kun lisäät kilpailijoita.',
  clubsPageCompetitorsCount: '{{count}} kilpailijaa',
  clubsLongNameInfo: 'Käytetään joukkuekilpailuissa, jos syötetty',
  competitorNumbersSync: 'Synkronoi kilpailijanumerot',
  competitorNumbersSyncInfo: 'Tällä sivulla voit synkronoida kahden tai useamman kilpailun kilpailijanumerot. Toiminto ei ole saatavilla liikuntalajeille.',
  edit: 'Muokkaa',
  editOfficialRights: 'Muokkaa toimitsijan oikeuksia',
  longName: 'Pitkä nimi',
  megaLinkImportTitle: 'Megalink-tulokset',
  megaLinkImportFile: 'Tiedoston sisältö',
  megaLinkImportContentsError: 'Tiedoston sisältö on virheellinen',
  megaLinkImportSuccess: 'Tulokset tallennettu',
  officialPageAddManyDescription: 'Tällä sivulla voit kutsua monta toimitsijaa kerralla. Listaa toimitsijoiden sähköpostiosoitteet ja jos haluat heille rajoitetut oikeudet, lisää perään piiri / seura alla olevan esimerkin mukaisesti. Henkilöiden täytyy olla rekisteröitynyt palveluun omilla sähköpostiosoitteillaan.',
  officialPageAddManyTitle: 'Kutsu monta toimitsijaa kilpailun toimitsijoiksi',
  officialPageAllCurrent: 'Kaikki nykyiset',
  officialPageAllowAddingClubs: 'Salli uusien piirien/seurojen lisäys',
  officialPageAllowSpecificClub: 'Salli kilpailijoiden lisäys vain tiettyyn piiriin/seuraan',
  officialPageAddingAllowed: 'Lisäys sallittu',
  officialPageCancelInvitation: 'Peruuta kutsu',
  officialPageCannotLimitUsagePre: 'Käyttöä ei voi rajata, koska',
  officialPageCannotLimitUsagePost: 'yhtään piiriä/seuraa ei ole lisätty',
  officialPageDeleteRightsConfirmation: 'Haluatko varmasti poistaa käyttäjän toimitsijaoikeudet tähän kilpailuun?',
  officialPageEmailsAndClubs: 'Sähköpostit ja mahdolliset piirit/seurat',
  officialPageFullRights: 'Täydet oikeudet',
  officialPageInvite: 'Kutsu toinen henkilö tämän kilpailun toimitsijaksi',
  officialPageNoLimitation: 'Ei rajausta',
  officialPageOnlyAddCompetitors: 'Anna käyttäjälle ainoastaan oikeudet lisätä kilpailijoita',
  officialPagePendingInvites: 'Odottaa rekisteröitymistä',
  officialPageRaceOfficials: 'Kilpailun toimitsijat',
  officialPageRequirement: 'Henkilön täytyy olla rekisteröitynyt palveluun omalla sähköpostiosoitteellaan.',
  officialPageSendInvitation: 'Lähetä kutsu',
  officialPageSendInvitations: 'Lähetä kutsut',
  officialRaceMenuHome: 'Yhteenveto',
  officialRaceMenuEdit: 'Perustiedot',
  officialRaceMenuCompetitors: 'Kilpailijat',
  officialRaceMenuStartList: 'Lähtöajat',
  officialRaceMenuHeatListGeneration: 'Erien arvonta',
  officialRaceMenuQualificationRoundHeatList: 'Alkukilpailu',
  officialRaceMenuFinalRoundHeatList: 'Loppukilpailu',
  officialRaceMenuHeats: 'Erät',
  officialRaceMenuQuickSave: 'Pikasyöttö',
  officialRaceMenuTimes: 'Ajat',
  officialRaceMenuEstimates: 'Arviot',
  officialRaceMenuShooting: 'Ammunta',
  officialRaceMenuShootingBySeries: 'Ammunta sarjoittain',
  officialRaceMenuShootingByHeats: 'Ammunta erittäin',
  officialRaceMenuCorrectDistances: 'Oikeat etäisyydet',
  officialRaceMenuCsv: 'CSV',
  officialRaceMenuTeamCompetitions: 'Joukkuek.',
  officialRaceMenuRelays: 'Viestit',
  officialRaceMenuOfficials: 'Toimitsijat',
  officialsCountMany: '{{count}} toimitsijaa',
  officialsCountOne: '1 toimitsija',
  save: 'Tallenna',
  update: 'Päivitä',
}
