/* eslint-disable max-len */
window.officialTranslations = {
  add: 'Öka',
  backToOfficialRacePage: 'Tillbaka till Sammanfattning-sida',
  cancel: 'Avbryt',
  clubsPageInfo: 'På den här sidan kan du öka klubbar och radera önodiga. Obs! Du kan öka klubbar också när du ökar tävlar.',
  clubsPageCompetitorsCount: '{{count}} tävlar',
  clubsLongNameInfo: 'Användas i lagtävlingar om sätt',
  edit: 'Redigera',
  longName: 'Langt namn',
  megaLinkImportTitle: 'Megalink-resultat',
  megaLinkImportFile: 'Fil',
  megaLinkImportContentsError: 'Filen har fel format',
  megaLinkImportSuccess: 'Resultaten sparats',
  officialRaceMenuHome: 'Sammanfattning',
  officialRaceMenuEdit: 'Basinformation',
  officialRaceMenuCompetitors: 'Tävlar',
  officialRaceMenuStartList: 'Starttider',
  officialRaceMenuBatchListGeneration: 'Heatlotteri',
  officialRaceMenuQualificationRoundBatchList: 'Grundtävling',
  officialRaceMenuFinalRoundBatchList: 'Final',
  officialRaceMenuBatches: 'Heat',
  officialRaceMenuQuickSave: 'Resultat',
  officialRaceMenuTimes: 'Tider',
  officialRaceMenuEstimates: 'Bedömning',
  officialRaceMenuShooting: 'Skytte',
  officialRaceMenuShootingBySeries: 'Skytte (klasser)',
  officialRaceMenuShootingByBatches: 'Skytte (heat)',
  officialRaceMenuCorrectDistances: 'Riktiga avstånd',
  officialRaceMenuCsv: 'CSV',
  officialRaceMenuTeamCompetitions: 'Lagtävlingar',
  officialRaceMenuRelays: 'Stafetter',
  officialRaceMenuOfficials: 'Funktionärer',
  save: 'Spara',
}
