window.translations = {
  account: 'Egna uppgifter',
  ageGroupShorterTrip: 'Åldersgrupp {{ageGroups}} har kortare sträcka',
  ageGroupsShorterTrip: 'Åldersgrupper {{ageGroups}} har kortare sträcka',
  allAnnouncements: 'Alla nyheter',
  allCompetitors: 'Alla tävlande',
  allClubs: 'Alla klubbar',
  allDistricts: 'Alla trakten',
  allHeats: 'Alla heat',
  allLevels: 'Alla nivåer',
  allRaces: 'Alla tävlingar',
  allSeries: 'Alla klasser',
  allSeriesStartTimesPdf: 'Starttider för alla klasser (PDF)',
  allSports: 'Alla grener',
  alsoCompetitorsFromClubs: 'Dessutom alla tävlande från klubben (tryck ctrl om du vill välja flera)',
  alsoCompetitorsFromDistricts: 'Dessutom alla tävlande från trakten (tryck ctrl om du vill välja flera)',
  announcements: 'Nyheter',
  answersTitle: 'Frågor och svar',
  appTitle: 'Hirviurheilu - Resultatservice för Jägarförbundets sportgrener',
  atLeast: 'åtminstone',
  backToCupHomePage: 'Tillbaka till cup-tävlingens hemsida',
  backToHomePage: 'Tillbaka till hemsida',
  backToPage: 'Tillbaka till sida {{pageName}}',
  heatList: 'Heatlista',
  heatListNotCreated: 'Heatlistan är inte färdig',
  heatListNotPublished: 'Heatlistan har ännu inte publicerats',
  cancelled: 'Inställd',
  captchaInfo: 'Vi vill kontrollera att du är inte en robot. Det rätta svaret är naturligtvis fyra.',
  captchaQuestion: 'Hur mycket är två plus två?',
  club: 'Klubb',
  clubs: 'Klubbar',
  comparisonTime: 'Jämförelsetid',
  competitor: 'Tävlande',
  competitor_DNS: 'Tävlande startade inte',
  competitor_DNF: 'Tävlande bröt loppet',
  competitor_DQ: 'Tävlande blev diskad',
  competitorsCountMany: '{{count}} tävlande',
  competitorsCountOne: '1 tävlande',
  competitorsPerSeries: 'Tävlande / klass',
  correctDistances: 'Korrekt avstånd',
  country: 'Land',
  countries: 'Länder',
  cupCompetitions: 'Deltävlingar',
  cupHome: 'Cup-tävlingens hemsida',
  cupPointsRule: 'Totalpoäng beräknas på grund av {{bestCompetitionsCount}} bäst resultat',
  cupPointsRuleTitle: 'Poängsberäkning',
  cupPointsRuleWithLast:
    'Totalpoäng beräknas på grund av den sista tävlingen och de andra tävlingarnas {{bestCompetitionsCount}} bäst resultat',
  cupPublicMessage: 'Cup-tävlingens organizatör informerar',
  cups: 'Cup-tävlingar',
  district: 'Trakt',
  districts: 'Trakter',
  downloadAllResults: 'Ladda ner alla resultat',
  downloadHeatList: 'Ladda ner heatlista',
  downloadHeatListPdf: 'Ladda ner heatlista som PDF-fil',
  downloadPressReport: 'Ladda ner pressraporten',
  downloadRelayCompetitorsPdf: 'Ladda ner startlistan som PDF-fil',
  downloadResultsCsv: 'Ladda ner resultaten som CSV-fil',
  downloadResultsPdf: 'Ladda ner resultaten som PDF-fil',
  downloadResultsPdfWithCompetitors: 'Ladda ner PDF (med tävlande)',
  downloadResultsPdfWithoutCompetitors: 'Ladda ner PDF (utan tävlande)',
  downloadStartListPdf: 'Ladda ner startlista som PDF-fil',
  downloadStartTimes: 'Ladda ner starttider',
  email: 'Epost',
  estimatePenalties: 'Bedömningsfinar',
  estimating: 'Bedömning',
  european_compak: 'Compak',
  european_rifle: 'Kulskytte',
  european_rifle1: 'Rådjur',
  european_rifle2: 'Räv',
  european_rifle3: 'Gems',
  european_rifle4: 'Vildsvin',
  european_shotgun: 'Trap och compak',
  european_trap: 'Trap',
  eventOtherRaces: 'Andra tävlingar i evenemanget',
  extraRound: 'Omskjutning',
  feedback: 'Feedback',
  feedbackRaceInfo: 'Om du vill skicka feedback för en tävlings organizatör, välj tävlingen som Mottagare av feedback',
  feedbackReceiver: 'Mottagare av feedback',
  feedbackReceiverCommon: 'Allmän Hirviurheilu-feedback',
  feedbackSentInfo: 'Om du lämnade din kontaktuppgifter, vi kontakter dig så snabbt som möjlig',
  feedbackThankYou: 'Tack för feedback',
  finalRound: 'Final',
  finalRoundHeatList: 'Finalens heatlista',
  finish: 'Mål',
  hideCompetitors: 'Dölj tävlande',
  hideCupCompetitions: 'Dölj deltävlingar',
  hideShots: 'Dölj skott',
  homePage: 'Hemsida',
  info: 'Info',
  latestAnnouncements: 'Senaste nyheter',
  leg: 'Sträcka',
  legNumber: 'Sträcka {{leg}}',
  legTime: 'Sträckatid',
  level_0: 'Andra',
  level_1: 'Distrikt',
  level_2: 'Regional',
  level_3: 'FM',
  level_4: 'Internationell',
  login: 'Logga in',
  name: 'Namn',
  navigate: 'Visa i Google Maps',
  noCompetitors: 'Inga tävlande',
  noCompetitorsOrStartTimes: 'Denna klass har inga tävlande eller så har de ännu inga starttider.',
  noCupSeries: 'Cup-sarjoja ei ole vielä määritetty',
  nordic_rifle_moving: 'Älg',
  nordic_rifle_standing: 'Rådjur',
  nordic_rifleMoving: 'Älg',
  nordic_rifleStanding: 'Rådjur',
  nordic_shotgun: 'Compak',
  nordic_trap: 'Trap',
  noResultReason_: 'Normal',
  noResultReason_DNS: 'Startade inte (DNS)',
  noResultReason_DNF: 'Avbröt (DNF)',
  noResultReason_DQ: 'Diskad (DQ)',
  noTeams: 'Inga lag',
  noTimeLimit: 'Nästa och slutade',
  numberShort: 'Nr',
  officialHomePage: 'Funktionärssidor',
  pdfPageBreaks: 'Sidbytningar mellan klasserna',
  personalCompetitions: 'Normaltävlingar',
  points: 'Poäng',
  press: 'Press',
  pressInfoUnfinishedRace: 'På den här sidan kan du hämta pressraporten, när tävlingen har slutats',
  pressReportInstructions: 'Dun kan kopiera resultraporten nedanför och bifoga den till exempel till din epost',
  prices: 'Priser',
  qAndA: 'Kysymyksiä ja vastauksia',
  qualificationRound: 'Grundtävling',
  qualificationRoundHeatList: 'Grundtävlingens heatlista',
  raceCancelledMessage: 'Tyvärr tävlingen är inställd',
  raceCancelledTitle: 'Tävlingen inställd',
  raceHomePage: 'Tävlingens hemsidor',
  raceMenuHome: 'Tävlingens hemsida',
  raceOrganizer: 'Tävlingens organizatör',
  racePublicMessage: 'Tävlingens organizatör informerar',
  raceResultsPdf: 'Alla resultat (PDF)',
  raceStarted: 'Tävlingen började {{time}}',
  raceStarts: 'Tävlingen börjar {{time}}',
  races: 'Tävlingar',
  races_future: 'Nästä tävlingar',
  races_past: 'Slutade tävlingar',
  races_today: 'Tävlingar i dag',
  races_yesterday: 'Tävlingar i går',
  races_tomorrow: 'Tävlingar i morgon',
  races_day_after_tomorrow: 'Tävlingar i övermorgon',
  races_this_week: 'Tävlingar på denna vecka',
  races_next_week: 'Tävlingar på nästa vecka',
  races_this_month: 'Tävlingar senare på denna månad',
  races_next_month: 'Tävlingar på nästa månad',
  races_later: 'Tävlingar senare',
  races_previously: 'Tidigare slutade tävlingar',
  races_latest: 'Senaste slutade tävlingar',
  racesNotFound: 'Inga tävlingar',
  raceSearchPlaceholder: 'Tävlings namn eller ort',
  raceUnfinished: 'Tävlingen ofärdig',
  raceUnfinishedDistancesLater: 'Tävlingen ofärdig. Precis avståndsdata publiceras, när tävlingen har slutat.',
  raceWithoutSeries: 'Tävlingen saknas klasser för tillfället',
  relay: 'Stafett',
  relayNotStarted: 'Stafetten har inte ännu börjat',
  relayPenaltySeconds_RUN:
    'Sakkoja ei juosta vaan ne lisätään aikaan. Arviointi: {{estimatePenaltySeconds}} s/sakko. Ammunta: {{shootingPenaltySeconds}} s/sakko.',
  relayPenaltySeconds_SKI:
    'Sakkoja ei hiihdetä vaan ne lisätään aikaan. Arviointi: {{estimatePenaltySeconds}} s/sakko. Ammunta: {{shootingPenaltySeconds}} s/sakko.',
  relays: 'Stafetter',
  relayStartTime: 'Stafettens starttid: {{time}}',
  relayWithoutStartTime: 'Stafetten har inte ännu starttid',
  relayWithoutTeams: 'Inga lagen tillsatt för stafetten ännu',
  reset: 'Radera',
  result: 'Resultat',
  resultRotation: 'Resultatskrets',
  resultRotationAutoScroll: 'Rulla sidan automatiskt',
  resultRotationInfo:
    'Välj åtminstone två klasser och starta resultatskrets. När du vill stoppa kretsen, kom tillbaka på den här sidan.',
  resultRotationSettings: 'Inställningar',
  resultRotationStart: 'Starta resultatskrets',
  resultRotationStop: 'Stoppa resultatskrets',
  results: 'Resultat',
  resultsInProgress: 'Resultat updaterad {{time}}',
  rifle: 'Kulskytte',
  rifleResults: 'Kulskyttes resultat',
  rifleTeamCompetition: 'Kulskyttes lagtävling',
  rifleTeamCompetitions: 'Kulskyttes lagtävlingar',
  search: 'Sök',
  searchRace: 'Sök tävling',
  secondsPerPage: 'Sekunder / sida',
  send: 'Skicka',
  sendFeedback: 'Skicka feedback',
  series: 'Klass',
  seriesPlural: 'Klasser',
  seriesShorterTrip: 'Klassen har kortare sträcka',
  seriesNoCompetitors: 'Inga tävlande i klassen',
  seriesNoStartList: 'Klassens startlist har inte ännu publicerats',
  seriesNotStarted: 'Klassen har inte ännu börjat',
  seriesPointsMethod1_SKI: '4 bedömningar, -1p/1m',
  seriesPointsMethod1_RUN: '4 bedömningar, -1p/1m',
  seriesPointsMethod2_SKI: '4 bedömningar, inga tidpoäng',
  seriesPointsMethod2_RUN: '4 bedömningar, inga tidpoäng',
  seriesPointsMethod3_SKI: '2 bedömningar, alla tävlande får 300 tidpoäng',
  seriesPointsMethod3_RUN: '2 bedömningar, alla tävlande får 300 tidpoäng',
  seriesPointsMethod4_SKI: '2 bedömningar, inga tidpoäng',
  seriesPointsMethod4_RUN: '2 bedömningar, inga tidpoäng',
  seriesStartTime: 'Klassens starttid',
  shooting: 'Skytte',
  shootingPenalties: 'Skyttefinar',
  shootingRulesPenalty: 'Straff för brott mot skjutregler',
  shootingTime: 'Skyttetid',
  shots: 'Skott',
  showAll: 'Visa alla',
  showCompetitors: 'Visa tävlande',
  showCupCompetitions: 'Visa deltävlingar',
  showOfficialResults: 'Visa formella resultaten',
  showShots: 'Visa skott',
  showUnofficialResults: 'Visa informella resultaten (inkl. all tävlande)',
  sport_EUROPEAN: 'Europeiskt jaktskytte',
  sport_ILMAHIRVI: 'Luftgevärsälg',
  sport_ILMALUODIKKO: 'Luftgevärstjäder',
  sport_METSASTYSHAULIKKO: 'Jaktskytte',
  sport_METSASTYSHIRVI: 'Älgskytte',
  sport_METSASTYSLUODIKKO: 'Tjäderskytte',
  sport_METSASTYSTRAP: 'Jägartrap',
  sport_NORDIC: 'Nordiskt jaktskytte',
  sport_PIENOISHIRVI: 'Pienoishirvi',
  sport_PIENOISLUODIKKO: 'Pienoisluodikko',
  sport_SKI: 'Älgskidskytte',
  sport_RUN: 'Älglöpning',
  sportsInfo: 'Information av grener',
  startList: 'Startlista',
  startLists: 'Startlista',
  startTime: 'Starttid',
  startUsage: 'Börja',
  team: 'Lag',
  team_DNS: 'Laget startade inte',
  team_DNF: 'Laget bröt loppet',
  team_DQ: 'Laget blev diskad',
  teamCompetitionResultsNotAvailable: 'Lagtävlingens resultat kan inte beräknas ännu',
  teamCompetition: 'Lagtävling',
  teamCompetitions: 'Lagtävlingar',
  tel: 'Telefon',
  timeTitle_RUN: 'Löpning',
  timeTitle_SKI: 'Skidning',
  totalPoints: 'Totalpoäng',
  totalResults: 'Resultat',
  track: 'Bana',
  unofficialCompetitor: 'Informella tävlande',
  unofficialShort: 'inf.',
  useQualificationRoundResult: 'Poäng räknas ut från resultaten från den grundtävlingarna',
}
